# You have to configure this ###################################################
title: The Pacific Current
# You should configure this ####################################################
url: http://thepacificcurrent.com
download_url: "http://thepacificcurrent.com/episodes"
subtitle: Local Island People doing Island Kine Tings
description: A podcast featuring interviews with the future and current leaders of Hawaii and how they are shaping the future we will soon call home. A mix of the creative, cultural, and business-minded people of the islands. For the people, by the people.
author: The Pacific Current
author_url: "http://thepacificcurrent.com/" # This is the URL of a site owned by the author (s. https://jsonfeed.org/version/1)
email: info@thepacificcurrent.com
keywords: [Hawaii, Business, Entrepreneurship, Island, Local, Culture, Polynesia, Pacific, Current]
itunes_categories: [Business]

episodes_per_feed_page: 100
# Date can be localized via date_de.rb plugin
date_format: "ordinal"

# You can configure this #######################################################
twitter_username: pacificcurrent
instagram_username: thepacificcurrent
facebook_username: thepacificcurrent 
language: en
explicit: 'no'  # 'yes'/'no'/clean
license: CC BY 4.0

## Itunes link ###########################################################
itunes_url: "https://itunes.apple.com/at/podcast/myname/id#myid#"
## Isso comments #########################################################
use_isso: no # set to 'yes' to include isso comments form

plugins:
  - jekyll-octopod 
  - jekyll-mentions
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-gist

#theme: Moon
