# Site wide configuration

title: "The Pacific Current"
description: "Coming soon to a podcast near you"
#if you modify locale please have a look at _data/messages.yml too
locale: en
#for meta name="author" :
author: The Pacific Current

#Target date in UTC / GMT
countdown:
  theme: red
  year: 2018
  month: 3
  day: 1
  hour: 0
  minute: 0

# Site owner
owner:
  name: Andrew Taeoalii
  email: info@thepacificcurrent.com
  twitter: "@pacificcurrent"
  google-plus:
  instagramm: "@thepacificcurrent"
  #Aboutlink = German "Impressum", provide url and caption (eg "Impressum")
  aboutlink:
    url: https://thepacificcurrent.com
    caption: The Pacific Current


# Jekyll configuration
sass:
  sass_dir: _sass
  style: compressed
permalink: /:categories/:title/
kramdown:
  toc_levels: 1..2
highlighter: rouge


exclude: ["lib", "config.rb", ".sass-cache", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "*.sublime-project", "*.sublime-workspace", "Gemfile", "Gemfile.lock", "README.md", "LICENSE", "node_modules", "Gruntfile.js", "package.json"]
